services:
  travelbuddyapi:
    container_name: travelbuddyapi
    build:
      context: ./TravelBuddyAPI
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"
    volumes:
      - ./keys:/root/.aspnet/DataProtection-Keys
