<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="mockCvData.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <ExcludeFromSingleFile>true</ExcludeFromSingleFile>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="payOS" Version="1.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BusinessObject\BusinessObject.csproj" />
    <ProjectReference Include="..\Repositories\Repositories.csproj" />
	  <PackageReference Include="PdfPig" Version="0.1.12" />
	  <PackageReference Include="PuppeteerSharp" Version="20.2.4" />

	  <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.0" />
	  <PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0" />



	  <PackageReference Include="QuestPDF" Version="2025.7.4" />
	  <PackageReference Include="StackExchange.Redis" Version="2.10.1" />
  </ItemGroup>

</Project>
